language: cpp

compiler: gcc

env:
  global:
    secure: "C4tE5UQtoItWxd+sSfj9vULLd0EjY5Ek/BentI/m1xz6tAOi+65RTjMEgz9OQZh1rlsExV4y9YEfV/JzZ3peLNypw3b2BaCum6LECkaEDob2aPR03u/DruTkGkXITUIFFh2hg0iQH2TZP9/0ZtQBRXqNbU+DnH8Rs1Q+kNcWoFU="

addons:
  coverity_scan:
    project:
      name: "rakhimov/scram"
    # description: "Simplified Command-line Risk Analysis Multi-tool"
    notification_email: "ol.rakhimov@gmail.com"
    build_command_prepend: "cmake .."
    build_command: "make -j 2"
    branch_pattern: "coverity-scan"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
    - sudo add-apt-repository -y ppa:beineri/opt-qt521
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    - sudo apt-get install -qq libboost-program-options1.48-dev
    - sudo apt-get install -qq libboost-filesystem1.48-dev
    - sudo apt-get install -qq libboost-system1.48-dev
    - sudo apt-get install -qq libboost-math1.48-dev
    - sudo apt-get install -qq libxml2-dev
    - sudo apt-get install -qq libxml++2.6-dev
    - sudo apt-get install -qq libgoogle-perftools-dev
    - sudo apt-get install -qq qt52base
    - sudo apt-get install -qq cmake

before_script:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - source /opt/qt52/bin/qt52-env.sh
    - mkdir build
    - cd build

script:
    - ../.no_build.sh

after_failure:
    - cat build-log.txt
