language: cpp

compiler: gcc

env:
  global:
    secure: "C4tE5UQtoItWxd+sSfj9vULLd0EjY5Ek/BentI/m1xz6tAOi+65RTjMEgz9OQZh1rlsExV4y9YEfV/JzZ3peLNypw3b2BaCum6LECkaEDob2aPR03u/DruTkGkXITUIFFh2hg0iQH2TZP9/0ZtQBRXqNbU+DnH8Rs1Q+kNcWoFU="

addons:
  coverity_scan:
    project:
      name: "rakhimov/SCRAM"
    # description: "Simplified Command-line Risk Analysis Multi-tool"
    notification_email: "olzhasrakhimov7@gmail.com"
    build_command_prepend: "cmake .."
    build_command: "make -j 2"
    branch_pattern: "coverity-scan"

before_install:
  - mkdir build
  - cd build
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install -qq libboost-program-options1.48-dev
  - sudo apt-get install -qq libboost-random1.48-dev
  - sudo apt-get install -qq libboost-filesystem1.48-dev
  - sudo apt-get install -qq libboost-system1.48-dev
  - sudo apt-get install -qq libxml2-dev
  - sudo apt-get install -qq libxml++2.6-dev

script:
    - ../.no_build.sh

after_failure:
    - cat build-log.txt
