sudo: required
dist: trusty

language: cpp

compiler: gcc

env:
    global:
        secure: "C4tE5UQtoItWxd+sSfj9vULLd0EjY5Ek/BentI/m1xz6tAOi+65RTjMEgz9OQZh1rlsExV4y9YEfV/JzZ3peLNypw3b2BaCum6LECkaEDob2aPR03u/DruTkGkXITUIFFh2hg0iQH2TZP9/0ZtQBRXqNbU+DnH8Rs1Q+kNcWoFU="

addons:
    coverity_scan:
        project:
            name: "rakhimov/scram"
        # description: "Command-line Risk Analysis Multi-tool"
        notification_email: "ol.rakhimov@gmail.com"
        build_command_prepend: "cmake .."
        build_command: "make -j 2"
        branch_pattern: "coverity-scan"
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libboost-program-options1.58-dev
            - libboost-filesystem1.58-dev
            - libboost-system1.58-dev
            - libboost-math1.58-dev
            - libboost-date-time1.58-dev
            - libxml2-dev
            - libxml++2.6-dev
            - libgoogle-perftools-dev
            - qt5-default
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:kojoley/boost'

before_script:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
    - mkdir build
    - cd build

script:
    - ../.no_build.sh

after_success:
    - cat build/cov-int/scm_log.txt

after_failure:
    - cat build-log.txt
